## YAML Template.
---
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
  file: /data/logs/${spring.application.name}/application.log
  pattern:
    file: '%d - %-5level - %msg%n'
    console:  '%d - %-5level - %msg%n'
hibernate.show_sql: true
hibernate.format_sql: true
hibernate.use_sql_comments: true
hibernate.default_schema: dbo
server:
    hostname: localhost
    port: 9001
spring:
    application.name:   hisolutions
    jpa:
      properties.hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform:  org.hibernate.dialect.SQLServer2012Dialect
      show-sql: true
      use_sql_comments: true
#      hibernate.naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
#      hibernate.naming-strategy: 'org.hibernate.cfg.Defau\u200cltNamingStrategy'
#      hibernate.ddl-auto: update
#        dialect:  org.hibernate.dialect.SQLServer2012Dialect
    datasource:
#      url:  jdbc:sqlserver://192.200.10.110;databaseName=HMSDev
      url:  jdbc:sqlserver://localhost;databaseName=HMSDev
      username: HISAdmin
      password: 5p1tf1r3
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 30
        minimum-idle: 2
        idle-timeout: 30000
#      driver-class-name:  com.microsoft.sqlserver.jdbc.SQLServerDriver
